### ISSUE TITLE
test 问题

### ISSUE THREAD

**Issue by 972461099** [CaiQiuYu/Simple-RCAN#1]
您好，感谢您分享代码，我训练了十几轮后，测试结果为如下情况，请问您知道是什么原因吗
![Screenshot from 2019-12-03 09-04-09](https://user-images.githubusercontent.com/23586956/69946044-c6b5d500-1525-11ea-80a7-e254fbc54c3c.png)

**Comment by CaiQiuYu** [comment]
我更新推断代码吧，有个地方忘记改了，抱歉，更改后你再测试看看

**Comment by CaiQiuYu** [comment]
你用新的代码测试看看，看有没有问题吧

**Comment by 972461099** [comment]
> 你用新的代码测试看看，看有没有问题吧
可以了，谢谢～
