### ISSUE TITLE
关于超分

### ISSUE THREAD

**Issue by ZHUXUHAN** [CaiQiuYu/Simple-RCAN#2]
老哥 我也是北邮的 我也参加了超分比赛 我看你好像不怎么提交了 能用下你的提交次数吗 老哥事后必有重谢

**Comment by CaiQiuYu** [comment]
今天的可以给你用，我们队还在等结果，做的有点晚了

**Comment by wulei2019** [comment]
> 今天的可以给你用，我们队还在等结果，做的有点晚了

老哥，今天你们提交吗？
